### PR TITLE
getTransaction calls should use "confirmed" commitment

### PR DESCRIPTION
**Pull request by leverageforsale**
This is a small issue, but I believe it is usually much better to query the blockchain with "confirmed" status when reading from the chain.

https://docs.solana.com/developing/clients/jsonrpc-api#configuring-state-commitment

> For processing many dependent transactions in series, it's recommended to use "confirmed" commitment, which balances speed with rollback safety.

The main issue here is speed. While I agree with finalized being better for total safety, in my experience- working at an aggregator that depends on real time accurate data (also writing the parser for mentioned aggregator), confirmed transactions 99.9% of the time end up being finalized. Rollbacks are extremely rare. Failures occur pre - "Finality" phase.

With the change to "confirmed" you can expect to have an accurate transaction without sacrificing speed, thereby improving UX. A valuable improvement when writing parsers that can be used in production environments.

### CODE REVIEW

**Comment by devDesu** [comment]
Thank you for your feedback! Maybe it's better to pass commitment level as a parameter? Or just use connection commitment level

**Comment by leverageforsale** [comment]
That is a much better solution, although I think getTransaction depends on Finality, which is a subset of commitment level.

https://solana-labs.github.io/solana-web3.js/modules.html#Finality

We could pass in a commitment parameter of type Finality that defaults to confirmed if not specified (I am pretty sure the default behavior of most solana methods is to default to confirmed/fastest minimum commitment level unless specified). If specified, since the only other option is finalized, that can also be passed in?

Does that sound like a solution?

**Comment by devDesu** [comment]
Yep, I believe we could add parameter after `flatten` to prevent method signature change.

Could you please implement it so I'll be able to merge the PR?

**Comment by leverageforsale** [comment]
@devDesu I just pushed the new commit. Let me know if you have any other requests for the PR. Thank you!!

**Comment by devDesu** [comment]
Thanks, everything looks fine

**Pull request merged**
